BEGIN TRANSACTION;

ALTER TABLE segment ALTER COLUMN indIP VARCHAR(255);
ALTER TABLE salle ALTER COLUMN nSalle VARCHAR(255);
ALTER TABLE logiciel ALTER COLUMN nLog VARCHAR(255);
ALTER TABLE poste ALTER COLUMN nPoste VARCHAR(255);

ALTER TABLE dateIns ALTER COLUMN installer int NULL;

COMMIT;